### ISSUE TITLE
crashes with calget AttributeError: 'list' object has no attribute 'today' 

### ISSUE THREAD

**Issue by sammcj** [directive0/HeadsUp#1]
Howdy,

Neat project! I just got a Vufine and wanted to give this a shot, but the HeadsUp app keeps crashing.

- MacOS Mojave 10.14.5
- Python 3.7.3
- `psutil requests pygame ics` all installed as required.

You seen a window being drawn briefly, then it dies with the below error when trying to do something with `calget.py`:

```
~/git/HeadsUp pip3 install psutil requests pygame ics


~/git/HeadsUp python3 main.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 205, in <module>
    tilelist[i].draw(page)
  File "/Users/samm/git/HeadsUp/tiles.py", line 902, in draw
    self.drawlayout()
  File "/Users/samm/git/HeadsUp/tiles.py", line 859, in drawlayout
    self.disparea.draw(self.info)
  File "/Users/samm/git/HeadsUp/tiles.py", line 688, in draw
    eventlist = events.GetTodaysEvents()
  File "/Users/samm/git/HeadsUp/calget.py", line 39, in GetTodaysEvents
    self.eventstoday = self.events.today(True)
AttributeError: 'list' object has no attribute 'today'

~/git/HeadsUp python3 --version
Python 3.7.3
```

**Comment by directive0** [comment]
Hi, yeah I know exactly what is causing this but can't fix it right this minute. I will make some changes and push a new version soon!

**Comment by directive0** [comment]
So I didn't quite fix it, I've disabled it as something seems to have broken. I think ics may have changed how events work, so its sort of broken for the moment.

I've recently gotten my vufine out again and want to work on this more. I will try to get ics working again, but at least for now it runs. Such as it is.

Sorry for the delay.
